### ISSUE TITLE
Give players a colored name

### ISSUE THREAD

**Issue by EmmaKnijn** [project-connecticut/ct-server#1]
I would like to have players have a cyan name. usually referred to as (dark_aqua) or &3.
Currently this is implemented through teams but this is quite jank

**Comment by khankul** [comment]
I vote for implementation of MiniMessage format so that we can use a brighter cyan color.

**Comment by EmmaKnijn** [comment]
We would also need to jerryrig other mods to support MiniMessage

**Comment by EmmaKnijn** [comment]
Regular players would be fine if they're white, but I would like contributers and admins to have other colors

**Comment by EmmaKnijn** [comment]
The prefixes supplied by luckperms are plenty to differentiate users, closing
